// src/hooks/useFolders.ts — entirely generated by createCrudHooks; the
// only hand-written piece is useFolders(parentId?) matching the existing
// call shape (getFolders(parentId?: string | null)) at the hook level,
// since that's where component call sites actually care about ergonomics
// — the underlying service stays the plain, interface-matching shape.
import { createCrudHooks } from "../client/createCrudHooks";
import { folderService } from "../services/folder.service";
import type { CreateFolderRequest, Folder, UpdateFolderRequest } from "../types/folder";

const folderHooks = createCrudHooks<Folder, CreateFolderRequest, UpdateFolderRequest>("folders", folderService);

export function useFolders(parentId?: string | null) {
  return folderHooks.useList(parentId ? { parentId } : undefined);
}

export const useFolder = folderHooks.useOne;
export const useCreateFolder = folderHooks.useCreate;
export const useUpdateFolder = folderHooks.useUpdate;
export const useDeleteFolder = folderHooks.useDelete;
